### DISCUSSION TITLE
Local only binds for docker-compose.yaml

### DISCUSSION THREAD

**Discussion by rept0id** [go-shiori/shiori#1101] [Feature requests]
Hello,

I'm saying from the very beginning that I don't know if such a thing would may cause any compatibility problems or break the expected experience for many people. I'm not even sure if it's needed or a good idea. I ask mostly to ask and to get your opinion about this. Such is the reason I say this here, as a discussion and I don't make a pull request.

So, my question is, why in the docker-compose.yaml, things not meant to be exposed, aren't they binded local-only ?

By that, I mean, instead of :
```
  postgres:
    image: postgres:13.18
    environment:
      POSTGRES_PASSWORD: shiori
      POSTGRES_USER: shiori
    ports:
      - "5432:5432"
```

To have :
```
  postgres:
    image: postgres:13.18
    environment:
      POSTGRES_PASSWORD: shiori
      POSTGRES_USER: shiori
    ports:
      - "127.0.0.1:5432:5432"
```

I'm aware that people that pull the image must, lets say in their docker-compose, expose only the things meant to be exposed, but still, **why in the world to allow someone to expose postgres** ?

**Ofc, if you find this a good idea, please let's make all together 100% sure that this wont break things for other people.**
