### DISCUSSION TITLE
Allow for a custom css configuration file for the reader mode

### DISCUSSION THREAD

**Discussion by ekianjo** [go-shiori/shiori#338] [Feature requests]
Hi, I love the integration of the reader mode - I was wondering if you could allow for a specific css file that could be an optional config file where we could customize how the reader mode looks?

**Comment by JoshuaCrewe** [comment]
Wallabag has this feature and it can be quite useful. It is a nice way to let people do their own styling and not have to deal with requests for style changes. Not sure how many of those this project gets though!

**Comment by Monirzadeh** [comment]
@ekianjo @JoshuaCrewe 
I test that, and we can do that easily (but not clean yet)
some consideration for this feature:
1. It will be widely, not per user. (is it important?)
2. Should be modifiable in UI, or it is enough just copy custom.css to /css?

What do you think?

Note to future me:
- it should not be affect e-book CSS (not tested yet but if affect that I prefer not add this feature)
- what should we do if CSS code is not valid?(my first test show browser ignore that, but do we need validation mechanism?)

**Reply by fmartingr** [reply]
I'd say that this should be a per-user feature configurable in the UI. Users can have a textbox where they add custom CSS styles that are injected into the pages. Unsure how wallabag handles this, but that's the base on how I see this happening.

Security wise, we need to cleanup anything non-css from the user input to avoid any kind of stored xss or things like that. 

@JoshuaCrewe can you provide examples on custom styling you found useful in the past?

**Reply by Monirzadeh** [reply]
In general, wallabag handle that this way
1. link `custom.css` in `content.html` in last link
2. user can edit that CSS to overrate default CSS.

I'm done that in one of my local branch and work fine.
Problem get a little complicated when you should do that per-user
If we need per-user, so somehow we should make `content.html` different for each user. Or call a variable inside that that link to user specific CSS.

**Reply by JoshuaCrewe** [reply]
@fmartingr I can indeed. The changes I made were very minimal. Things like :
- Making it use a system font
- I like  bolder titles
- A few spacing tweaks
- A smaller line length on smaller screens
- Getting rid of the box shadows 

This was all on the reader view. I think I intended to do the archive page but haven't got round to it yet.

This is a before and after. It is basically all the stuff that isn't worth opening a PR for because it is so minor and subjective but all the reasons self hosting is worth it:

![2023-07-03_08-46](https://github.com/go-shiori/shiori/assets/12238901/32a0ba87-072b-4f22-989b-35c886fbb256)
![2023-07-03_08-39](https://github.com/go-shiori/shiori/assets/12238901/ba4e7429-ec47-4693-b704-6981fbaf852a)

**Reply by Monirzadeh** [reply]
@JoshuaCrewe can i have css to check that on other language?

**Reply by JoshuaCrewe** [reply]
@Monirzadeh Absolutely.

```css
body {
  background-color: #fff !important;
  font-family: system-ui, -apple-system,
    /* Firefox supports this but not yet `system-ui` */ "Segoe UI", Roboto,
    Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"; /* 2 */
}

#article {
  box-shadow: none !important;
}

#article > header > h1 {
  margin: 6rem 0 3rem;
  font-weight: 800;
  text-align: center;
}

#article aside .tools {
  justify-content: center;
}

#article aside .tools .stats {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

@media (max-width: 800px) {
  #article article {
    width: 70%;
    margin: 0 auto;
  }
}

.dark-theme #article {
  box-shadow: none;
}

.dark-theme body,
.dark-theme main #content,
.dark-theme #article,
.dark-theme .card,
.dark-theme .card-panel,
.dark-theme .card .card-reveal,
.dark-theme .card-stacked .preview:not(.preview--default),
.dark-theme .card .preview:not(.preview--default),
.dark-theme .collapsible-header,
.dark-theme .collection,
.dark-theme .dropdown-content,
.dark-theme .nav-panel-add,
.dark-theme .nav-panel-search,
.dark-theme .side-nav,
.dark-theme .side-nav .collapsible-body,
.dark-theme .side-nav.fixed .collapsible-body,
.dark-theme .tabs {
  background-color: #101010;
}

```
