### DISCUSSION TITLE
First time use, can't login

### DISCUSSION THREAD

**Discussion by mohuddle** [go-shiori/shiori#604] [Q&A]
I'm on Fedora 36, after downloading the executable, I ran an import of my exported Pocket bookmarks. Then I ran the following:
./shiori serve --portable -p 9191

In a browser, I am able to navigate to the shiori server page. When I try shiori/gopher, the screen refreshes and the URL changes to http://localhost:9191/login?dst=%2F#home . But the login screen remains. Below is output from the terminal where I started shiori

I removed /.local/share/shiori/shiori.db and restarted the webserver, same response. If I key in shiori and a password other than gopher, I get "sql: no rows in result set (500)" above the login screen.

I've tried from two different browsers on my Linux workstation as well as my phone, same response.
///

INFO[0000] Serve shiori in :9191 /                      
WARN[0012] GET /                                         proto=HTTP/1.1 remote="[::1]:49770" reqlen=0 size=49 status=301
INFO[0012] GET /login?dst=%2F                            proto=HTTP/1.1 remote="[::1]:49770" reqlen=0 size=4299 status=200
INFO[0012] GET /css/source-sans-pro.min.css              proto=HTTP/1.1 remote="[::1]:49770" reqlen=0 size=1078 status=200
INFO[0012] GET /css/fontawesome.min.css                  proto=HTTP/1.1 remote="[::1]:49780" reqlen=0 size=54348 status=200
INFO[0012] GET /css/stylesheet.css                       proto=HTTP/1.1 remote="[::1]:49792" reqlen=0 size=15673 status=200
INFO[0012] GET /js/vue.min.js                            proto=HTTP/1.1 remote="[::1]:49796" reqlen=0 size=93390 status=200
INFO[0012] GET /js/url.min.js                            proto=HTTP/1.1 remote="[::1]:49810" reqlen=0 size=3798 status=200
INFO[0013] GET /css/fonts/source-sans-pro-v13-latin-200.woff2  proto=HTTP/1.1 remote="[::1]:49810" reqlen=0 size=15824 status=200
INFO[0013] GET /css/fonts/source-sans-pro-v13-latin-regular.woff2  proto=HTTP/1.1 remote="[::1]:49796" reqlen=0 size=16112 status=200
INFO[0013] GET /css/fonts/source-sans-pro-v13-latin-600.woff2  proto=HTTP/1.1 remote="[::1]:49780" reqlen=0 size=15948 status=200
INFO[0013] GET /css/fonts/fa-solid-900.woff2             proto=HTTP/1.1 remote="[::1]:49792" reqlen=0 size=74348 status=200
INFO[0013] GET /res/favicon.ico                          proto=HTTP/1.1 remote="[::1]:49792" reqlen=0 size=5430 status=200
INFO[0019] POST /api/login                               proto=HTTP/1.1 remote="[::1]:49792" reqlen=58 size=145 status=200
WARN[0019] GET /                                         proto=HTTP/1.1 remote="[::1]:49792" reqlen=0 size=49 status=301
INFO[0019] GET /login?dst=%2F                            proto=HTTP/1.1 remote="[::1]:49792" reqlen=0 size=4299 status=200

**Comment by karbak** [comment]
Identical experience on Fedora 37 with the shiori 1.5.4 release executable.  There's nothing in the account table - looks like the code path in webserver/handler-api.go which seems to be set up to handle the hardcoded default login/password isn't working, but I can't find a way to trigger any useful logging either.

**Reply by mohuddle** [reply]
For grins, I'm going to install Linux Mint on my workstation and try it over there and see if I get different results. I can't imagine it would be at that level, but since I'm swapping OS, might as well try.

**Reply by mohuddle** [reply]
No change. Same response on Linux Mint. Fresh download of Shiori 1.5.4. User shiori, password gopher. It accepts the user/pass combo (no errors returned) but does not load the page beyond the login page.

**Reply by fmartingr** [reply]
Hey, I just tried a fresh install on my mac(the only thing I have available right now) & vivaldi and it works. Which browser and version are you using? it may be a problem with the frontend rather than the backend. Accounts in Shiori are kind of confusing at the moment, since the `shiori/gopher` is not an account per se since its hardcoded (so you don't need an account to use with the CLI or the server). Please let me know more information so I can take a look.

I will try under a linux machine this coming week.

**Reply by mohuddle** [reply]
Well what do you know. Using Firefox, it works.

Same on phone. Firefox works. With Chromium based browsers, I was able to login from my phone finally, but not all the menu/buttons were there.

**Comment by sommerper** [comment]
I did a `docker-compose up --force-recreate --build -d` and facing the same issue.
![image](https://github.com/go-shiori/shiori/assets/1512048/e5746a35-7eb7-4eff-8268-1581f72eb054)

I did have to change the default db port since it was already taken.

```
# Docker compose for development purposes only
version: "3"
services:
  shiori:
    build:
      context: .
      dockerfile: Dockerfile.compose
    container_name: shiori
    ports:
      - "8080:8080"
    volumes:
      - "./dev-data:/srv/shiori"
      - ".:/src/shiori"
    restart: unless-stopped
    links:
      - "postgres"
      - "mariadb"
    environment:
      SHIORI_DBMS: mysql
      SHIORI_DIR: /srv/shiori
      SHIORI_PG_USER: shiori
      SHIORI_PG_PASS: shiori
      SHIORI_PG_NAME: shiori
      SHIORI_PG_HOST: postgres
      SHIORI_PG_PORT: 5433
      SHIORI_MYSQL_USER: shiori
      SHIORI_MYSQL_PASS: shiori
      SHIORI_MYSQL_NAME: shiori
      SHIORI_MYSQL_ADDRESS: (mariadb)

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: shiori
      POSTGRES_USER: shiori
    ports:
      - "5433:5432"

  mariadb:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shiori
      MYSQL_USER: shiori
      MYSQL_PASSWORD: shiori
    ports:
      - "3306:3306"
```
