### ISSUE TITLE
security context is necessary for Kubernetes

### ISSUE THREAD

**Issue by opswhisperer** [go-shiori/shiori#791]
This is really just a documentation issue. If you're deploying to k8s and not using hostPath but a real persistent storage (i.e. Longhorn) you'll need to set the security context to match the user you created in the Dockerfile. Otherwise you get a permissions issue and the `Failed to open database: unable to open database file: out of memory (14)` error from sqlite 

``` 
spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
```
