### ISSUE TITLE
Windows Binaries are being released as .tar.gz's

### ISSUE THREAD

**Issue by torculus** [go-shiori/shiori#851]
Just like it says, the releases page distributes Windows `.exe`'s in `.tar.gz` files. These can't be opened natively on Windows, and it's blocking submission of `shiori` to `winget`

Here's the relevant section in goreleaser:
https://github.com/go-shiori/shiori/blob/595cb45a2ce7031926ead1f1e1324e673e36d676/.goreleaser.yaml#L29

Another golang project I follow [solves this](https://github.com/twpayne/chezmoi/blob/master/.goreleaser.yaml#L99) with this setting
```yaml
  format_overrides:
  - goos: windows
    format: zip
```
